### ISSUE TITLE
强烈要求来一发 百姓网的 logo icon

### ISSUE THREAD

**Issue by 9nix00** [baixing/baicons#7]
最近在做第三方登录，这个需求还是明确的

**Comment by amio** [comment]
我们有 Logo 使用规范吗？
钱袋跟文字版貌似都是正式 Logo，但不知道用途场景有什么分别

按我以前的认识，钱袋是百姓的视觉标识，但是我们的主站上又基本忽略掉了这个形象
不知道它的设计用途是什么。

**Comment by hax** [comment]
这个问题建议问York。

在 2015年1月5日 下午5:11，Amio <notifications@github.com>写道：

> 我们有 Logo 使用规范吗？
> 钱袋跟文字版貌似都是正式 Logo，但不知道用途场景有什么分别
>
> 按我以前的认识，钱袋是百姓的视觉标识，但是我们的主站上又基本忽略掉了这个形象
> 不知道它的设计用途是什么。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baixing/baicons/issues/7#issuecomment-68683225>.
>



-- 
hax

**Comment by aijuan** [comment]
我曾经下百姓网app的时候，看到图标是个钱袋，疑惑了很久这货真的是百姓网的app而不是个山寨货？。。。

**Comment by amio** [comment]
问了下 York，
> 钱袋曾近作为APP的logo，但后来不用了。现在是标准的百姓网的logo。

**Comment by yorkliang** [comment]
嗯，我们在2013年中的时候在APP上用钱袋的logo，那个时候强调二手、强调省钱，网站也准备做一些调整。但后来整个对外宣传还是全类目的，所以就不用了。在2014年6月份确定了APP采用标准的“百姓”logo。现在如果看到钱袋的logo，都换成百姓的logo。
